### ISSUE TITLE
Adicionar atalhos de teclado

### ISSUE THREAD

**Issue by JPTIZ** [thurbridi/py-rudolph#29]
Sugestões:

| Atalho                              | Comando          |
|-------------------------------------|------------------|
| <kbd>Ctrl</kbd> + <kbd>N</kbd>      | Novo             |
| <kbd>Ctrl</kbd> + <kbd>O</kbd>      | Abrir            |
| <kbd>Ctrl</kbd> + <kbd>S</kbd>      | Salvar           |
| <kbd>Ctrl</kbd> + <kbd>A</kbd>      | Adicionar objeto |
| <kbd>Ctrl</kbd> + <kbd>E</kbd>      | Editar objeto    |
| <kbd>Del</kbd>                                 | Excluir objeto    |
| <kbd>&larr;&uarr;&rarr;&darr;</kbd> | Mover objeto     |

**Comment by thurbridi** [comment]
Vai dar um pouco mais de trabalho que o previsto...

**Comment by thurbridi** [comment]
> Vai dar um pouco mais de trabalho que o previsto...

ATALHOS DE TECLADO NO GLADE TÃO NAQUELE MENU EDIT BIZONHO!

valeu @JPTIZ
